# NAMESPACE
apiVersion: v1
kind: Namespace
metadata:
  name: book-search

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: book-search-config
  namespace: book-search
data:
  # RabbitMQ connection
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "guest"
  # Exchange
  APP_RABBITMQ_DIRECT_EXCHANGE: "search.direct.exchange"
  APP_RABBITMQ_TOPIC_EXCHANGE: "search.topic.exchange"
  APP_RABBITMQ_FANOUT_EXCHANGE: "search.fanout.exchange"
  # Queues
  APP_RABBITMQ_REQUEST_QUEUE: "search.request.queue"
  # Routing Keys
  APP_RABBITMQ_REQUEST_ROUTING: "search.request"

  APP_RABBITMQ_REQUEST_CONCURRENCY: "2-10"
  APP_RABBITMQ_RESULT_CONCURRENCY: "2-40"
  APP_RABBITMQ_SOURCE_CONCURRENCY: "2-10"
  # WebSocket 
  APP_WEBSOCKET_TOPIC_PREFIX: "/list/search/"

---
apiVersion: v1
kind: Secret
metadata:
  name: book-search-secret
  namespace: book-search
type: Opaque
stringData:
  SPRING_RABBITMQ_PASSWORD: "guest"
  APP_API_TRANSLATE_KEY: "YOUR_API_KEY"
  APP_API_SPELLCHECK_KEY: "YOUR_API_KEY"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: book-search
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: book-search-secret
              key: SPRING_RABBITMQ_PASSWORD
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
      volumes:      
      - name: rabbitmq-data        
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: book-search
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
    nodePort: 31672
  type: NodePort

---
# GATEWAY — Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-search-gateway
  namespace: book-search
  labels:
    app: book-search-gateway
spec:
  selector:
    matchLabels:
      app: book-search-gateway
  template:
    metadata:
      labels:
        app: book-search-gateway
    spec:
      initContainers:
      - name: wait-rabbitmq
        image: busybox
        command: ['sh', '-c',
          'until nc -z rabbitmq 5672; do echo "Waiting for RabbitMQ..."; sleep 3; done']
      containers:
      - name: gateway
        image: vinee04/booksearch-gateway-1.0.0:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: book-search-config
        env:
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: book-search-secret
              key: SPRING_RABBITMQ_PASSWORD
        - name: APP_API_TRANSLATE_KEY
          valueFrom:
            secretKeyRef:
              name: book-search-secret
              key: APP_API_TRANSLATE_KEY
        - name: APP_API_SPELLCHECK_KEY
          valueFrom:
            secretKeyRef:
              name: book-search-secret
              key: APP_API_SPELLCHECK_KEY
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "768Mi"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: book-search-gateway
  namespace: book-search
spec:
  selector:
    app: book-search-gateway
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP    #Nginx se proxy vao

---
# WORKER
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-search-worker
  namespace: book-search
  labels:
    app: book-search-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-search-worker
  template:
    metadata:
      labels:
        app: book-search-worker
    spec:
      initContainers:
      - name: wait-rabbitmq
        image: busybox
        command: ['sh', '-c',
          'until nc -z rabbitmq 5672; do echo "Waiting for RabbitMQ..."; sleep 3; done']
      containers:
      - name: worker
        image: vinee04/booksearch-worker-1.0.0:v0.0.1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: book-search-config
        env:
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: book-search-secret
              key: SPRING_RABBITMQ_PASSWORD
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "900m"
            memory: "768Mi"
        livenessProbe:
          exec:
            command: ["sh", "-c", "pgrep -f java || exit 1"]
          initialDelaySeconds: 30
          periodSeconds: 20
          failureThreshold: 3

---
# NGINX FRONTEND — Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-search-frontend
  namespace: book-search
  labels:
    app: book-search-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-search-frontend
  template:
    metadata:
      labels:
        app: book-search-frontend
    spec:
      containers:
      - name: nginx
        image: vinee04/booksearch-frontend-1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: book-search-frontend
  namespace: book-search
spec:
  selector:
    app: book-search-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
---