apiVersion: v1
kind: PersistentVolume

metadata:
  name: rabbitmq-pv

spec:
  capacity:
    storage: 2Gi

  accessModes:
  - ReadWriteOnce

  storageClassName: manual

  persistentVolumeReclaimPolicy: Retain

  local:
    path: /data/rabbitmq

  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker